---
  name: ci

  on:
    workflow_dispatch:
    push:
      branches:
        - master
    pull_request:

  permissions:
    contents: read

  ## Concurrency only allowed in the main branch.
  ## So old builds running for old commits within the same Pull Request are cancelled
  concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

  jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-go@v4
          with:
            go-version-file: 'go.mod'

        - name: Lint
          run: |-
            go mod tidy && git diff --exit-code
            gofmt -l . | read && echo "Code differs from gofmt's style. Run 'gofmt -w .'" 1>&2 && exit 1 || true
            go vet
    go-test:
      strategy:
        fail-fast: false
        matrix:
          go-version: ['1.15', '1.16']
          os: [macos-latest, ubuntu-latest, windows-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-go@v4
          with:
            go-version: ${{ matrix.go-version }}
            cache: true
            cache-dependency-path: '**/go.sum'

        - name: Build
          run: go build

        - name: Test
          run: go test -v ./...

        - name: Run examples
          run: ${{ startsWith(matrix.os,'windows') && '.github/examples.bat' || '.github/examples.sh' }}
    test:
      if: always()
      runs-on: ubuntu-latest
      needs:
        - go-test
      steps:
        - id: check
          uses: elastic/apm-pipeline-library/.github/actions/check-dependent-jobs@current
          with:
            needs: ${{ toJSON(needs) }}
        - run: ${{ steps.check.outputs.isSuccess }}
